export const URLS = {
    LANDING: '/',
    LOGIN: '/login',
    HOME: '/app',
    JOBS: '/app/jobs',
    RATE: '/app/rate',
    RATE_DEMO: '/app/rate/demo',
    RATE_INTERVIEW: '/app/rate/[interviewId]',
    CANDIDATES: '/app/candidates',
    FLOW: '/app/flow',
    COMPANY: '/app/company',
    EDIT_COMPANY: '/app/company/edit',
    SETUP_COMPANY: '/app/setup-company',
    JOB: '/app/jobs/[jobId]',
    CREATE_A_JOB: "/app/create-job",
    MY_INTERVIEWS: '/app/my-interviews',
    MY_INTERVIEW: '/app/my-interviews/[interviewId]',
    RECORD_AN_INTERVIEW: '/app/record-an-interview',
    SUPPORT: '/app/support',
    PROFILE: '/app/profile',
    APPLY: '/apply/[applyJobId]',
    RECORD: '/apply/[applyJobId]/record',
    PUBLIC_JOB: '/jobs/[applyJobId]',
    DID_CALLBACK: '/did-callback',
    TERMS_AND_CONDITIONS: '/terms-and-conditions',
    PRIVACY_POLICY: '/privacy-policy',
    DEMO_INTERVIEW: '/jobs/bd1f9940-eccf-4a59-8de4-d0179a298e34'
}

export const DOMAIN = 'https://theinterview.io'