export const URLS = {
    HOME: '/',
    LOGIN: '/login',
    JOBS: '/app/jobs',
    RATE: '/app/rate',
    ARCHIVE: '/app/archive',
    FLOW: '/app/flow',
    COMPANY: '/app/company',
    SETUP_COMPANY: '/app/setup-company',
    JOB: '/app/jobs/[jobId]',
    CREATE_A_JOB: "/app/create-job",
    MY_VIDEOS: '/app/my-videos',
    RECORD_AN_INTERVIEW: '/app/record-an-interview',
    SUPPORT: '/app/support',
    PROFILE: '/app/profile',
    APPLY: '/apply/[applyJobId]',
    RECORD: '/apply/[applyJobId]/record',
    PUBLIC_JOB: '/jobs/[applyJobId]',
}

